### ISSUE TITLE
使用现有翻译流程还是迁移到 Sphinx / gettext / Transifex？

### ISSUE THREAD

**Issue by greyli** [greyli/flask-docs-zh#21]
起初的翻译流程设想在 https://github.com/flaskcwg/meta/issues/1 。基本流程就是直接翻译英文文档源文件（参考 README），然后追踪 Flask 文档的变动并手动更新到译文。

现在的问题是这个方式也许并不是合理的翻译流程。不过我对 Sphinx / gettext / Transifex 的工作流程还不够熟悉，需要进一步了解。欢迎评论指出两种方式的优缺点，以及后一种流程的基本运作方式，或是其他相关想法。

Sphinx / gettext / Transifex 相关参考文档：https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

**Comment by frostming** [comment]
直接覆盖了英文原文会导致后续的变更追踪更困难（diff不出来原文哪些地方有变更）

如果基于babel/gettext可以用自动化action生成待翻译的po文件（这个文件是可以增量更新的）然后扔到transifex协作。后者有词汇表功能方便校对。

**Comment by greyli** [comment]
我明天看下怎么安排和调整翻译流程。

**Comment by greyli** [comment]
现在仓库重置了，添加了 po 文件，不过我考虑直接编辑 po 文件就足够了。如果用户需要的话，可以用 po 编辑器。
