### ISSUE TITLE
仓库已重置，启用 Sphinx / gettext 翻译流程

### ISSUE THREAD

**Issue by greyli** [greyli/flask-docs-zh#23]
基于 #21 的讨论，翻译流程改为使用 po 文件，而不是直接编辑源文件。

因为原仓库删除了 Flask 仓库原有的 commit，所以为了能够和 Flask 仓库同步变动，重置了这个仓库。已经 fork 的话请删除重新创建仓库。另外相关 PR 已经关闭（#14、#17、#18、#22），请后续重新创建。抱歉！

**Comment by rosekc** [comment]
```po
"Language-Team: LANGUAGE <LL@li.org>\n"
```
这一行要怎么填啊

**Comment by greyli** [comment]
> 这一行要怎么填啊

这一行不要动，只改动 Last-Translator 那一行即可。

**Comment by greyli** [comment]
@rosekc 记得先在 README 标记/认领要翻译的章节。
